// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xsufidncfilmixxnjizy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzdWZpZG5jZmlsbWl4eG5qaXp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4OTU4MDksImV4cCI6MjA2ODQ3MTgwOX0.lHz2X_piqQ-NJSN3iQM9IKgy0YVvIXgfnE6hMEDZ26E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});